/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gdkcvpkbjcjfresoydvd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdka2N2cGtiamNqZnJlc295ZHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTUzMzEsImV4cCI6MjA3Mzk3MTMzMX0.MOY4KvS3bHzGjbpJreNSh7hGM4TbyqM05Lql-4Uaf_Q"
